stages:
- build
- test
- sonarQube

build:
 stage: build
 script:
    - cd songify-backend
    - ./gradlew build -x test
    
test:
  stage: test
  script:
    - cd songify-backend
    - ./gradlew test
    
sonarQube:
    stage: sonarQube
    script:
    - cd songify-backend
    - gradlew sonarqube ^ -Dsonar.login=1c7e2825316567d64649d95818633c6d34a7dc00
    
after_script:
  - echo "End CI"
  - exit