stages:
- Build
- Tests
- Static Analysis
- Deploy

Build:
 stage: Build
 script:
    - cd songify-backend
    - ./gradlew build -x test
    
Unit Tests:
  stage: Tests
  script:
    - cd songify-backend
    - ./gradlew test
    
e2e Cypress:
  stage: Tests
  script:
   - cd songify-frontend
   - npx cypress run --browser chrome --spec cypress/integration/init.spec.js
  
SonarQube:
    stage: Static Analysis
    script:
    - cd songify-backend
    - ./gradlew sonarqube "-Dsonar.login=1c7e2825316567d64649d95818633c6d34a7dc00"
  
Docker Build:
    stage: Deploy
    script:
    - echo "docker build script"
  
after_script:
  - echo "End CI"
  - exit