stages:
- Build
- Tests
- Static Analysis
- Deploy

Build:
 stage: Build
 script:
    - cd songify-backend
    - ./gradlew build -x test
    
Unit Tests:
  stage: Tests
  script:
    - cd songify-backend
    - ./gradlew test
    
e2e Cypress:
  stage: Tests
  script:
   - cd songify-frontend
   - echo "cypress stage"
  
SonarQube:
    stage: Static Analysis
    script:
    - cd songify-backend
    - ./gradlew sonarqube "-Dsonar.login=1c7e2825316567d64649d95818633c6d34a7dc00"
  
Backend:
    stage: Deploy
    script:
    - cd songify-backend
    - docker build -t songifybackend . 
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PW
    - docker push davekhaki/songifybackend
  
Frontend:
    stage: Deploy
    script:
    - cd songify-frontend
    - docker build -t davekhaki/songifyfrontend .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PW
    - docker push davekhaki/songifyfrontend
  
after_script:
  - echo "End CI"
  - exit