stages:
- build
- test

build:
 stage: build
 script:
    - cd songify-backend
    - ./gradlew build -x test
    
test:
  stage: test
  script:
    - cd songify-backend
    - ./gradlew test
    
after_script:
  - echo "End CI"
  - exit