stages:
- build
- test
- sonarQube

build:
 stage: build
 script:
    - cd songify-backend
    - ./gradlew build -x test
    
test:
  stage: test
  script:
    - cd songify-backend
    - ./gradlew test
    
sonarQube:
    stage: sonarQube
    script:
    - cd songify-backend
    - ./gradlew sonarqube
    
after_script:
  - echo "End CI"
  - exit