stages:
- Build
- Tests
- Sonar

build:
 stage: build
 script:
    - cd songify-backend
    - ./gradlew build -x test
    
Unit:
  stage: Tests
  script:
    - cd songify-backend
    - ./gradlew test
    
Cypress:
  stage: Tests
  script:
   - echo "cypress stage"
  
sonarQube:
    stage: sonarQube
    script:
    - cd songify-backend
    - ./gradlew sonarqube "-Dsonar.login=1c7e2825316567d64649d95818633c6d34a7dc00"
    
after_script:
  - echo "End CI"
  - exit