FROM node:13.12.0-alpine
WORKDIR /songify-frontend
ENV PATH /songify-frontend/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./

RUN npm install
RUN npm install react-scripts@3.4.1 -g 

COPY . ./

RUN npm run build

ENTRYPOINT ["npm", "start"]